image: node:20

default:
  tags:
    - docker

pages:
  cache:
    paths:
    - node_modules/
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
